name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v1
            - name: Setup Go
              uses: actions/setup-go@v2
            - name: Tidy
              run: go mod tidy
            - name: Lint
              run: go vet ./...
            - name: Tests
              run: go test ./... -v -timeout 0
